<?php

define('ALGOLIA_APP_ID', 'SEU_ALGOLIA_APP_ID');
define('ALGOLIA_SEARCH_KEY', 'SUA_ALGOLIA_SEARCH_ONLY_KEY');
define('ALGOLIA_INDEX_NAME', 'magento2_default_products');
define('AGENT_SECRET_TOKEN', 'SEU_TOKEN_SECRETO_FORTE_COM_NO_MINIMO_32_CARACTERES');
